"""Configuration module"""
from config.prompts import (
    PROFILE_PARSER_SYSTEM_PROMPT,
    PROFILE_PARSER_USER_PROMPT,
    EMAIL_GENERATOR_SYSTEM_PROMPT,
    EMAIL_GENERATOR_USER_PROMPT,
    RELEVANCE_ANALYSIS_PROMPT
)

__all__ = [
    "PROFILE_PARSER_SYSTEM_PROMPT",
    "PROFILE_PARSER_USER_PROMPT",
    "EMAIL_GENERATOR_SYSTEM_PROMPT",
    "EMAIL_GENERATOR_USER_PROMPT",
    "RELEVANCE_ANALYSIS_PROMPT"
]
