# Source Generated with Decompyle++
# File: prompts.cpython-313.pyc (Python 3.13)

'''Prompt templates for AI agents'''
PROFILE_PARSER_SYSTEM_PROMPT = 'You are a professional resume parser. Extract structured information from resumes and return it in JSON format.\n\nFocus on extracting:\n1. Personal information (name, location)\n2. Current role and company\n3. Education history\n4. Work experience\n5. Skills and competencies\n\nBe precise and extract only information that is explicitly stated in the resume.'
PROFILE_PARSER_USER_PROMPT = 'Parse the following resume text and extract structured information:\n\n{resume_text}\n\nReturn a JSON object with the following structure:\n{{\n  "name": "string",\n  "current_company": "string",\n  "current_role": "string",\n  "location": "string",\n  "education": [\n    {{\n      "school": "string",\n      "degree": "string",\n      "graduation_year": integer\n    }}\n  ],\n  "skills": ["string"],\n  "experiences": [\n    {{\n      "company": "string",\n      "role": "string",\n      "duration": "string"\n    }}\n  ]\n}}'
EMAIL_GENERATOR_SYSTEM_PROMPT = 'You are a professional networking expert specializing in writing personalized cold emails for coffee chats and informational interviews.\n\nYour emails should:\n1. Be concise (<150 words)\n2. Reference 1-2 specific connection points naturally\n3. Be genuine and professional (not overly formal)\n4. Have a clear call-to-action (15-min call or coffee)\n5. Avoid cliches and generic phrases\n\nDo not:\n- Use excessive flattery\n- Make assumptions about their time or interests\n- Write overly long emails\n- Use salesy language'
EMAIL_GENERATOR_USER_PROMPT = 'Write a personalized cold email for the following:\n\nYour background:\n{user_profile}\n\nContact information:\nName: {contact_name}\nTitle: {contact_title}\nCompany: {contact_company}\n\nConnection points:\n{connection_points}\n\nWrite a professional email requesting a brief coffee chat or 15-minute call. The email should be under 150 words and naturally reference the strongest connection points.'
RELEVANCE_ANALYSIS_PROMPT = 'Analyze the relevance between the user\'s profile and the contact based on the following connection points:\n\nUser Profile:\n{user_profile}\n\nContact:\n{contact_info}\n\nIdentify all connection points and categorize them as:\n- Same company (current or past)\n- Same location\n- Similar role/industry\n- Shared connections (if available)\n\nReturn a JSON object with a "connection_points" array:\n{{\n  "connection_points": [\n    {{\n      "type": "company",\n      "value": "Google",\n      "strength": 0.9\n    }}\n  ]\n}}'
